// Generated by `npm run accounts` — do not edit by hand.
// Devnet test accounts from OffCKB. Addresses only; never private keys.
export type DevAccount = { index: number; address: string; lockArgs: string };

export const DEV_ACCOUNTS: DevAccount[] = [
  {
    "index": 0,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvwg2cen8extgq8s5puft8vf40px3f599cytcyd8",
    "lockArgs": "0x8e42b1999f265a0078503c4acec4d5e134534297"
  },
  {
    "index": 1,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt435c3epyrupszm7khk6weq5lrlyt52lg48ucew",
    "lockArgs": "0x758d311c8483e0602dfad7b69d9053e3f917457d"
  },
  {
    "index": 2,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvarm0tahu0qfkq6ktuf3wd8azaas0h24c9myfz6",
    "lockArgs": "0x9d1edebedf8f026c0d597c4c5cd3f45dec1f7557"
  },
  {
    "index": 3,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0xt7prh3dy3gu9z45svp89q0d6f6c46cg9dp9mn",
    "lockArgs": "0xe65f823bc5a48a38515690604e503dba4eb15d61"
  },
  {
    "index": 4,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvkvhntcxtxas4lejj0z9uz62usduuy8rcwg4fr9",
    "lockArgs": "0x9665e6bc1966ec2bfcca4f11782d2b906f38438f"
  },
  {
    "index": 5,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgdl92j7574rgmc4w3x00y93kk6g3lggqq23mmmd",
    "lockArgs": "0x0df9552f53d51a378aba267bc858dada447e8400"
  },
  {
    "index": 6,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtgxxytk22s9wnwwq4hcegveqrs0slckjc2gkygd",
    "lockArgs": "0x683188bb29502ba6e702b7c650cc80707c3f8b4b"
  },
  {
    "index": 7,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2n90aegmjtzzx3gavv5w8xuw6276qpn9s4x74d7",
    "lockArgs": "0x532bfb946e4b108d14758ca38e6e3b4af6801996"
  },
  {
    "index": 8,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfes2kz7jynml9vpy0009dmw7xv9gj7mkgzxwxsx",
    "lockArgs": "0x3982ac2f4893dfcac091ef795bb778cc2a25edd9"
  },
  {
    "index": 9,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq264vuxaz5lf7rfwan8f3ccr6nklmm4k4gwtzp2q",
    "lockArgs": "0x5aab386e8a9f4f869776674c7181ea76fef75b55"
  },
  {
    "index": 10,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0kegwq3fq2k0gqug5ejvx0p7xznzs6jrg890q3w",
    "lockArgs": "0xf6ca1c08a40ab3d00e2299930cf0f8c298a1a90d"
  },
  {
    "index": 11,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2uhqycsfpjnsazuuckgxhyay96pglv89svgrrcn",
    "lockArgs": "0x5cb8098824329c3a2e731641ae4e90ba0a3ec396"
  },
  {
    "index": 12,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq23dyezsr2l7vggzx07ydsapp50rxvde3qslv5ac",
    "lockArgs": "0x516932280d5ff3108119fe2361d0868f1998dcc4"
  },
  {
    "index": 13,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqt6svzzmk47kfefflnztzxl0txxyl2ps8cyvd734",
    "lockArgs": "0x7a83042ddabeb27294fe62588df7acc627d4181f"
  },
  {
    "index": 14,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg5zmlgu0savkdzxh6lxkes7l8mm70awlq3lw7yk",
    "lockArgs": "0x1416fe8e3e1d659a235f5f35b30f7cfbdf9fd77c"
  },
  {
    "index": 15,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0jgmflnk224vng3w4mfqpg0yzkmxl4syqtwnm8g",
    "lockArgs": "0xf246d3f9d94aab2688babb4802879056d9bf5810"
  },
  {
    "index": 16,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2wc22ey0w7rdfzsdgq07fxp6968xxu0jcuc7xwl",
    "lockArgs": "0x4ec295923dde1b522835007f9260e8ba398dc7cb"
  },
  {
    "index": 17,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwh4djww473zaaf2kjun9axhfl74dy3vxctp93d8",
    "lockArgs": "0xd7ab64e757d1177a955a5c997a6ba7feab49161b"
  },
  {
    "index": 18,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvm52pxjfczywarv63fmjtyqxgs2syfffq2348ad",
    "lockArgs": "0x9ba28269270223ba366a29dc96401910540894a4"
  },
  {
    "index": 19,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq2prryvze6fhufxkgjx35psh7w70k3hz7c3mtl4d",
    "lockArgs": "0x4118c8c16749bf126b22468d030bf9de7da3717b"
  }
];
